/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("Calendar.java-application-conventions")
}

dependencies {
    // https://mvnrepository.com/artifact/mysql/mysql-connector-java
    implementation("mysql:mysql-connector-java:8.0.33")
}
