/*
 * This file was generated by the Gradle 'init' task.
 */

import ua.nure.calendar.Micronaut;
import io.micronaut.gradle.MicronautRuntime
import io.micronaut.gradle.MicronautTestRuntime

plugins {
    id("io.micronaut.application")
    id("Calendar.java-application-conventions")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":services"))

    implementation(Micronaut.Netty.lib)
    implementation(Micronaut.Runtime.lib)
    implementation(Micronaut.Management.lib)
}

micronaut {
    runtime(MicronautRuntime.NETTY)
    testRuntime(MicronautTestRuntime.JUNIT_5)
    version.set(Micronaut.version)
    processing {
        incremental.set(true)
        annotations.add("ua.nure.calendar")
    }
}

application {
    // Define the main class for the application.
    mainClass.set("ua.nure.calendar.web.Application")
}
