/*
 * This file was generated by the Gradle 'init' task.
 */

import ua.nure.calendar.Micronaut;
import io.micronaut.gradle.MicronautRuntime
import io.micronaut.gradle.MicronautTestRuntime

plugins {
    id("Calendar.java-application-conventions")
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation(project(":services"))

    implementation("com.sparkjava:spark-core:2.9.4")

    implementation("com.google.code.gson:gson:2.10")



}

application {
    // Define the main class for the application.
    mainClass.set("ua.nure.calendar.web.Application")
}
