

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("Calendar.java-application-conventions")
}

dependencies {
    implementation(project(":persistent"))
    // https://mvnrepository.com/artifact/org.mockito/mockito-core
    testImplementation("org.mockito:mockito-core:2.1.0")
}
